import 'package:get/get.dart';

class LocaleString extends Translations {
  static String nameName = "You first";
  static String noOrderFee = "We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals";

  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          "Welcome back to\'LogIn": "Welcome back to\'LogIn",
          "Enter Your Email": "Enter Your Email",
          "Email": "Email",
          "Password": "Password",
          "Login In": "Login In",
          "Hi Admin..": "Hi Admin..",
          "Dining": "Dining",
          "Delivery": "Delivery",
          "User List": "User List",
          "Customers": "Customers",
          "Vendors": "Vendors",
          "Coupons List": "Coupons List",
          "Vendor Category": "Vendor Category",
          "Product Category": "Product Category",
          "Pages List": "Pages List",
          "FAQ": "FAQ",
          "Orders": "Orders",
          "Change Language": "Change Language",
          "Settings": "Settings",
          "Image Slider": "Image Slider",
          "Logout": "Logout",
          "Total Sale": "Total Sale",
          "Total Orders": "Total Orders",
          "Total Profit": "Total Profit",
          "Total Products": "Total Products",
          "Customer Users List": "Customer Users List",
          "Add Customer": "Add Customer",
          "Create Account": "Create Account",
          "Enter Your Name": "Enter Your Name",
          "Name": "Name",
          "Mobile Number": "Mobile Number",
          "Save": "Save",
          "Restaurant Name": "Restaurant Name",
          "Enter your email": "Enter your email",
          "Enter your password": "Enter your password",
          "Confirm password": "Confirm password",
          "Enter your Confirm password": "Enter your Confirm password",
          "Address": "Address",
          "Category": "Category",
          "Select category": "Select category",
          "About Us": "About Us",
          "Upload Restaurant Images or Videos": "Upload Restaurant Images or Videos",
          "Upload Restaurant Menu Card": "Upload Restaurant Menu Card",
          "Image Gallery": "Image Gallery",
          "Choose From Gallery": "Choose From Gallery",
          "PromoCode Name": "PromoCode Name",
          "Code": "Code",
          "Discount": "Discount",
          "Max Discount": "Max Discount",
          "Start Date": "Start Date",
          "End Date": "End Date",
          "Add Coupon": "Add Coupon",
          "Add Vendor Category": "Add Vendor Category",
          "Vendor Category Name": "Vendor Category Name",
          "Description": "Description",
          "Accepted file types: JPEG, Doc, PDF, PNG": "Accepted file types: JPEG, Doc, PDF, PNG",
          "Title": "Title",
          "Select Picture From": "Select Picture From",
          "Camara": "Camara",
          "Gallery": "Gallery",
          "Edit Pages": "Edit Pages",
          "Pages": "Pages",
          "Long Description": "Long Description",
          "FAQ List": "FAQ List",
          "Question": "Question",
          "Answer": "Answer",
          "Orders Details": "Orders Details",
          "Order ID": "Order ID",
          "Selected Items": "Selected Items",
          "Customer Details": "Customer Details",
          "Customer Name": "Customer Name",
          "Customer Number": "Customer Number",
          "Subtotal": "Subtotal",
          "Service Fees": "Service Fees",
          "Total": "Total",
          "Order Completed": "Order Completed",
          "Complete Order": "Complete Order",
          "Order Rejected": "Order Rejected",
          "Accept Order": "Accept Order",
          "Reject Order": "Reject Order",
          "Add": "Add",
          "Log In": "Log In",
          "Vendor Users List": "Vendor Users List",
          "Restaurant Registration": "Restaurant Registration",
          "Coupon List": "Coupon List",
          "Add Product Category": "Add Product Category",
        },

        // french Language
        'fr_FR': {
          "Enter Your Email": "Entrez votre adresse e-mail",
          "Email": "E-mail",
          "Password": "Mot de passe",
          "Login In": "Connexion",
          "Hi Admin..": "Bonjour Admin..",
          "Dining": "Restauration",
          "Delivery": "Livraison",
          "User List": "Liste des utilisateurs",
          "Customers": "Clients",
          "Vendors": "Fournisseurs",
          "Coupons List": "Liste des coupons",
          "Vendor Category": "Catégorie du fournisseur",
          "Product Category": "Catégorie de produit",
          "Pages List": "Liste des pages",
          "FAQ": "FAQ",
          "Orders": "Commandes",
          "Change Language": "Changer la langue",
          "Settings": "Paramètres",
          "Image Slider": "Carrousel d'images",
          "Logout": "Déconnexion",
          "Total Sale": "Vente totale",
          "Total Orders": "Total des commandes",
          "Total Profit": "Bénéfice total",
          "Total Products": "Total des produits",
          "Customer Users List": "Liste des utilisateurs clients",
          "Add Customer": "Ajouter un client",
          "Add": "Ajouter",
          "Create Account": "Créer un compte",
          "Enter Your Name": "Entrez votre nom",
          "Name": "Nom",
          "Mobile Number": "Numéro de téléphone portable",
          "Save": "Enregistrer",
          "Restaurant Name": "Nom du restaurant",
          "Enter your email": "Entrez votre adresse e-mail",
          "Enter your password": "Entrez votre mot de passe",
          "Confirm password": "Confirmez le mot de passe",
          "Enter your Confirm password": "Confirmez le mot de passe",
          "Address": "Adresse",
          "Category": "Catégorie",
          "Select category": "Sélectionnez une catégorie",
          "About Us": "À propos de nous",
          "Upload Restaurant Images or Videos": "Téléchargez des images ou des vidéos de restaurant",
          "Upload Restaurant Menu Card": "Téléchargez la carte du menu du restaurant",
          "Image Gallery": "Galerie d'images",
          "Choose From Gallery": "Choisir depuis la galerie",
          "PromoCode Name": "Nom du code promo",
          "Code": "Code",
          "Discount": "Remise",
          "Max Discount": "Remise maximale",
          "Start Date": "Date de début",
          "End Date": "Date de fin",
          "Add Coupon": "Ajouter un coupon",
          "Add Vendor Category": "Ajouter une catégorie de fournisseur",
          "Vendor Category Name": "Nom de la catégorie de fournisseur",
          "Description": "Description",
          "Accepted file types: JPEG, Doc, PDF, PNG": "Types de fichiers acceptés : JPEG, Doc, PDF, PNG",
          "Title": "Titre",
          "Select Picture From": "Sélectionnez une image depuis",
          "Camera": "Caméra",
          "Gallery": "Galerie",
          "Edit Pages": "Modifier les pages",
          "Pages": "Pages",
          "Long Description": "Description longue",
          "FAQ List": "Liste des FAQ",
          "Question": "Question",
          "Answer": "Réponse",
          "Orders Details": "Détails des commandes",
          "Order ID": "ID de commande",
          "Selected Items": "Articles sélectionnés",
          "Customer Details": "Détails du client",
          "Customer Name": "Nom du client",
          "Customer Number": "Numéro du client",
          "Subtotal": "Sous-total",
          "Service Fees": "Frais de service",
          "Total": "Total",
          "Order Completed": "Commande terminée",
          "Complete Order": "Terminer la commande",
          "Order Rejected": "Commande rejetée",
          "Accept Order": "Accepter la commande",
          "Reject Order": "Rejeter la commande"
        },
      };
}
